name: StaffSecure
description: Give your players the option to have to register
version: 1.0-A
website: www.harry5573.co.uk
author: Harry5573
main: com.harry5573.staffsecure.StaffSecure
commands:
  login:
    description: Login command for staff
  password:
    description: Set password command for staff
  staffsecure:
    description: Main plugin command
  resetpassword:
    description: Console command to reset passwords